name: Check and deploy project 

on: 
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Checks

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install deps
      run: yarn install

    - name: Check with eslint
      run: yarn lint

    - name: Run tests
      if: always()
      run: yarn test

    - name: Run e2e tests
      env:
        POSTGRES_DB: postgres
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      if: always()
      run:
          echo $POSTGRES_DB &&
          echo $POSTGRES_USERNAME &&
          echo $POSTGRES_PASSWORD &&
          yarn test:e2e
